name: GearzBukkitPermissions
version: 1.2
authors: [Jake0oo0]
description: Bukkit Permissions Manager
main: net.cogz.permissions.bukkit.GearzBukkitPermissions
commands:
  permissions:
    description: Permissions command.
  group:
    description: Group management command.
  player:
    description: Player management command.
