name: GearzHub
version: 1.0
main: net.cogz.gearz.hub.GearzHub
description: TBNR Hub
website: http://tbnr.net
authors: [Twister915, Thecraftgod, NoyHillel1]
depend: [Gearz]
commands:
  setcannon:
    description: Create a cannon.
  delcannon:
    description: Delete a cannon.
  setspawn:
    description: Sets the spawn
  spawn:
    description: Sends player to spawn
    aliases: [s]
  world:
    description: Teleports sender to target world
  head:
    description: Gives the sender the target players head
  setWarp:
    description: Sets a warp
    aliases: [setWarpStar, warpStar]
  delWarp:
    description: Deletes a warp
    aliases: [delWarpStart]
  magicsign:
    description: Gives you a magic edit sign
    aliases: [ editsign, signedit ]