name: Gearz
version: 1.1
authors: [Twister915, xIGBClutchIx, Thecraftgod, pokuit]
description: o, dem gearz
main: net.tbnr.gearz.Gearz
depend: [ProtocolLib]
load: STARTUP
commands:
  nick:
    description: Nickname.
  realname:
    description: Checks a player's real name.
  game:
    description: Game manager command
  map:
    description: Gives info about the map.
  settings:
    description: Lists settings
  set:
    description: Sets setting to specified value
  get:
    description: Gets the value of the setting
  toggle:
    description: Toggles a setting, if applicable
permissions:
  gearz.test:
    default: op